server:
  port: 8081

spring:
  datasource:
    db1:
      url: jdbc:mysql://localhost:13306/test
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    db2:
      url: jdbc:mysql://localhost:23306/test
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver


  jta:
    transaction-manager-id: txManager


